os: linux
services:
- docker
sudo: required
language: python
env:
  global:
  - CONAN_UPLOAD=1
  - CONAN_REFERENCE="libcxx/3.8.0"
  - CONAN_USERNAME="smspillaz"
  - CONAN_CHANNEL="stable"
  - CONAN_TOTAL_PAGES=4
  - secure: 0mdHaQnY1ut6zF3lqsjOcl6lTKfrq44mO5sQftJSINBlI4VxV9gvJAkTLLnsivSpAb/1gHDcOaJMxL2QwaXGbK+qyZ/ppXS2Lh9dXice/bkPxwjjHUcl6A0g3imIoOUPlGa4gyrSmn/Q6ITotysfWpVNDO5SKo20DNxZ6xGk0ZZWYUJv00WXUCEeu2ubpy3sDuS4bB2J36ahVTTy0UzfhN7vH6iDtMqBqPRG3+uBSq8WW+tEPXNd/6DblCF5st/+gSVDFCbzJG1IhVdABrAUXHH+Kx3x7cy8nnmYcE7dIJN3jFPkIatzyUXpAP5T6TZgZAwMMQQDyXX3h+UgESWFJ9bMQ+SAn2X914hPAJ8STox2aNyNzI+6KF7FGQNEb+3mXK3WeZAgFRBTf2THQ3FLdLK44xaEq9gvZ+r0e31zWRUbE++WOtjAxSD4zuKpxQAWkGXRwPjzYjc1qqLsa5AgtD5Vb9tPIo6wWHOjeSnGYmuLZyod0dSrkPBhj45yfuEROwtQiQikTHAZCIlJBgbFkhI1IeqH34/rCOfBtSDa9D6ZCv7UNk+2LOS9gUagnf3jfuFt+p+aiqwvGzcy9H4elqfbzlqfDo8UzvB8+hfk7NXXccB04mvCNZIBlB7j5ccuER2pzez0S8rBrrfvNosnwySca8RqsPiDhKXJzqrwrIo=
  matrix:
  - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
matrix:
  include:
  - os: osx
    osx_image: xcode7.1
    language: generic
    env: CONAN_CURRENT_PAGE=1
  - os: osx
    osx_image: xcode7.1
    language: generic
    env: CONAN_CURRENT_PAGE=2
  - os: osx
    osx_image: xcode6.4
    language: generic
    env: CONAN_CURRENT_PAGE=1
  - os: osx
    osx_image: xcode6.4
    language: generic
    env: CONAN_CURRENT_PAGE=2
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
